apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  name: taskapp.k8s.local
spec:
  kubernetesVersion: 1.28.0
  cloudProvider: aws
  channel: stable
  configBase: s3://taskapp-kops-state- 418884736531/taskapp.k8s.local
  dnsType: gossip
  networkID: vpc-039c8217b3e046442
  networking:
    calico: {}
  topology:
    masters: private
    nodes: private
    bastion:
      bastionPublicName: bastion.taskapp.k8s.local
    dns:
      type: Private
  subnets:
  - name: us-east-1a
    type: Private
    zone: us-east-1a
    id: subnet-0b536e78469c7c02b
  - name: us-east-1b
    type: Private
    zone: us-east-1b
    id: subnet-097c007897b237e17
  - name: us-east-1c
    type: Private
    zone: us-east-1c
    id: subnet-05196dd9a77d932b8
  - name: utility-us-east-1a
    type: Utility
    zone: us-east-1a
    id: subnet-0e3bcd27861ee737e
  - name: utility-us-east-1b
    type: Utility
    zone: us-east-1b
    id: subnet-0166cfa46e09374b2
  - name: utility-us-east-1c
    type: Utility
    zone: us-east-1c
    id: subnet-0fe5b55de902198b9
  etcdClusters:
  - name: main
    etcdMembers:
    - instanceGroup: control-plane-us-east-1a
      name: a
    - instanceGroup: control-plane-us-east-1b
      name: b
    - instanceGroup: control-plane-us-east-1c
      name: c
    backups:
      backupStore: s3://taskapp-kops-state- 418884736531/taskapp.k8s.local/backups/etcd/main
  - name: events
    etcdMembers:
    - instanceGroup: control-plane-us-east-1a
      name: a
    - instanceGroup: control-plane-us-east-1b
      name: b
    - instanceGroup: control-plane-us-east-1c
      name: c
    backups:
      backupStore: s3://taskapp-kops-state- 418884736531/taskapp.k8s.local/backups/etcd/events
  masterPublicName: api.taskapp.k8s.local
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  name: control-plane-us-east-1a
  labels:
    kops.k8s.io/cluster: taskapp.k8s.local
spec:
  role: Master
  machineType: t3.micro
  minSize: 1
  maxSize: 1
  subnets:
  - us-east-1a
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  name: control-plane-us-east-1b
  labels:
    kops.k8s.io/cluster: taskapp.k8s.local
spec:
  role: Master
  machineType: t3.micro
  minSize: 1
  maxSize: 1
  subnets:
  - us-east-1b
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  name: control-plane-us-east-1c
  labels:
    kops.k8s.io/cluster: taskapp.k8s.local
spec:
  role: Master
  machineType: t3.micro
  minSize: 1
  maxSize: 1
  subnets:
  - us-east-1c
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  name: nodes-us-east-1a
  labels:
    kops.k8s.io/cluster: taskapp.k8s.local
spec:
  role: Node
  machineType: t3.micro
  minSize: 1
  maxSize: 1
  subnets:
  - us-east-1a
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  name: nodes-us-east-1b
  labels:
    kops.k8s.io/cluster: taskapp.k8s.local
spec:
  role: Node
  machineType: t3.micro
  minSize: 1
  maxSize: 1
  subnets:
  - us-east-1b
---
apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  name: nodes-us-east-1c
  labels:
    kops.k8s.io/cluster: taskapp.k8s.local
spec:
  role: Node
  machineType: t3.micro
  minSize: 1
  maxSize: 1
  subnets:
  - us-east-1c